[WIP] Manage logging in PPE
pfnet/pytorch-pfn-extras pull request #173
Opened 2021-05-28 06:04 UTC by emcastillo

2021-05-28 06:07 UTC, kmaehashi commented
Could you avoid using or configuring the root (default) logger? Please create a dedicated logger instance for PPE and use it from modules in PPE.

2021-05-28 06:43 UTC, kmaehashi commented on pytorch_pfn_extras/__init__.py
> +def configureLogging(filename=None, level=logging.ERROR):
```suggestion
def configureLogging(filename=None, level='ERROR'):
```

2021-07-07 07:50 UTC, emcastillo commented
I think this can be reviewed

2021-07-13 06:25 UTC, kmaehashi requested changes

2021-07-13 06:25 UTC, kmaehashi commented on pytorch_pfn_extras/logging.py
> +def configure_logging(filename=None, level='ERROR'):
This should be a private method and without arguments as users cannot change the filename / level after importing PPE.

```suggestion
def _configure_logging():
```

2021-07-13 06:25 UTC, kmaehashi commented on pytorch_pfn_extras/__init__.py
> +logging.configure_logging()
```suggestion
logging._configure_logging()
```

2021-07-13 06:25 UTC, kmaehashi commented on pytorch_pfn_extras/logging.py
> +    filename = os.environ.get('PPE_LOG_FILENAME', filename)
```suggestion
    filename = os.environ.get('PPE_LOG_FILENAME', None)
```

2021-07-13 06:25 UTC, kmaehashi commented on pytorch_pfn_extras/logging.py
> +    level = os.environ.get('PPE_LOG_LEVEL', level)
```suggestion
    level = os.environ.get('PPE_LOG_LEVEL', 'ERROR')
```

2021-07-13 06:25 UTC, kmaehashi commented on pytorch_pfn_extras/logging.py
> +        _logger.setLevel(logging.INFO)
```suggestion
        _logger.setLevel(logging.INFO)
        _logger.warning(f'invalid PPE_LOG_LEVEL ({level}); using INFO')
```

2021-07-13 06:25 UTC, kmaehashi commented on pytorch_pfn_extras/training/extensions/_snapshot.py
> +print(logger)
```suggestion
```

2021-07-15 02:09 UTC, emcastillo commented
Fixes applied :)

2021-07-15 12:07 UTC, kmaehashi commented
Thanks! Could you check this? https://github.com/emcastillo/pytorch-pfn-extras/pull/1

2021-07-15 13:56 UTC, kmaehashi commented
/test

2021-07-15 13:56 UTC, kmaehashi approved these changes

2021-07-15 14:42 UTC, kmaehashi commented
/test

2021-07-16 05:33 UTC, merged