Fix manager.extend to revive support of non Extension object argument
pfnet/pytorch-pfn-extras pull request #206
Opened 2021-07-13 12:59 UTC by asi1024

https://github.com/pfnet/pytorch-pfn-extras/pull/200#discussion_r668716056

2021-07-13 13:54 UTC, kmaehashi commented
/test

2021-07-13 13:54 UTC, kmaehashi requested changes

2021-07-13 13:54 UTC, kmaehashi commented on pytorch_pfn_extras/training/manager.py
> +            extension = extension_module.make_extension()(extension)
Could you add test for this?

2021-07-15 07:35 UTC, asi1024 commented
@kmaehashi PTAL.

2021-07-15 11:23 UTC, kmaehashi requested changes

2021-07-15 11:23 UTC, kmaehashi commented on pytorch_pfn_extras/training/manager.py
> +                    "2: Define custom extension class that overrides "
```suggestion
                    "2: Define custom extension class that inherits "
```

2021-07-15 11:23 UTC, kmaehashi commented on pytorch_pfn_extras/training/manager.py
> +                    "2: Define custom extension class that overrides "
Could revert support for methods and functions as well?

2021-07-15 12:14 UTC, kmaehashi requested changes
LGTM except for minor comments!

2021-07-15 12:14 UTC, kmaehashi commented on pytorch_pfn_extras/training/extension.py
>  class _CallableExtension(Extension):
I think now it's better to name it as:
```suggestion
class _WrappedExtension(Extension):
```

2021-07-15 12:14 UTC, kmaehashi commented on pytorch_pfn_extras/training/extension.py
> +    return ext if isinstance(ext, Extension) else _CallableExtension(ext)
```suggestion
def _as_extension(ext) -> Extension:
    return ext if isinstance(ext, Extension) else _WrappedExtension(ext)
```

2021-07-15 12:14 UTC, kmaehashi commented on pytorch_pfn_extras/training/manager.py
> +        extension = extension_module._get_extension(extension)
```suggestion
        extension = extension_module._as_extension(extension)
```

2021-07-15 12:14 UTC, kmaehashi commented on pytorch_pfn_extras/training/extension.py
> +    """Decorator to make given functions into Extension object.
The decorator no longer returns Extension object.
```suggestion
    """Decorator to make given function into an extension.
```

2021-07-15 15:08 UTC, asi1024 commented
/test

2021-07-15 15:29 UTC, kmaehashi approved these changes

2021-07-15 15:29 UTC, kmaehashi commented
Thanks, LGTM!

2021-07-15 15:41 UTC, merged