Add `ppe.nn.EnsureShapeAndDtype`
pfnet/pytorch-pfn-extras pull request #340
Opened 2021-09-13 07:57 UTC by emcastillo

Closes #147

2021-09-13 07:57 UTC, emcastillo commented
/test

2021-09-13 09:04 UTC, kmaehashi commented
* How about supporting `None` in shape, like `ensure_shape`? I think users are likely to want to allow any size for the batch dimension.
* Maybe better having a wrapper API `ppe.ensure(tensor, *, shape=None, dtype=None, ...)`?
* Could you add tests to run these checks under jit?

2021-09-13 09:27 UTC, emcastillo commented
> How about supporting None in shape, like ensure_shape? I think users are likely to want to allow any size for the batch dimension.

I think it is currently supported, shape should be optional.

> Maybe better having a wrapper API ppe.ensure(tensor, *, shape=None, dtype=None, ...)?

This is nice to add, but the module should be kept too so we can use it inside `torch.nn.Sequential`.

> Could you add tests to run these checks under jit?

Sure, I wonder if it will be directly exported to onnx identity. Conditionals will be ignored in the exported module.
But they should be triggered while exporting.

2021-09-13 09:29 UTC, kmaehashi commented
> I think it is currently supported, shape should be optional.

Ah, I meant, e.g. `tf.ensure_shape(x, [None, 3])` to mark the first dimension unknown (allow any value)

2021-09-13 09:30 UTC, emcastillo commented
seems nice :)

2021-09-14 01:44 UTC, emcastillo commented
/test

2021-09-14 01:44 UTC, emcastillo commented
PTAL!

2021-09-14 01:45 UTC, emcastillo commented
/test

2021-09-14 02:28 UTC, emcastillo commented
/test

2021-09-14 02:41 UTC, emcastillo commented
/test

2021-09-14 03:37 UTC, emcastillo commented
/test

2021-09-21 08:13 UTC, kmaehashi reviewed
LGTM except for

2021-09-21 08:13 UTC, kmaehashi commented on tests/pytorch_pfn_extras_tests/nn_tests/modules_tests/test_ensure_shape.py
> +        ((3,), (2,)),
Better to test 0-dim case here?

2021-10-07 02:45 UTC, emcastillo commented
/test

2021-10-07 02:46 UTC, emcastillo commented
Addressed review comments! thanks!

2021-10-08 05:36 UTC, kmaehashi requested changes
LGTM except for minor comment.
Could you add new APIs to https://github.com/pfnet/pytorch-pfn-extras/blob/master/docs/source/reference/index.rst ?

2021-10-08 05:36 UTC, kmaehashi commented on pytorch_pfn_extras/nn/modules/ensure_shape.py
> +            shape: Optional[Tuple[int]] = None,
mypy failed in CI as `shape` may contain None.

```suggestion
            shape: Optional[Tuple[Optional[int]]] = None,
```

2021-10-08 05:36 UTC, kmaehashi commented on pytorch_pfn_extras/nn/modules/ensure_shape.py
> +        shape: Optional[Tuple[int]] = None,
```suggestion
        shape: Optional[Tuple[Optional[int]]] = None,
```

2021-10-08 05:40 UTC, emcastillo commented
/test

2021-10-08 07:58 UTC, emcastillo commented
/test

2021-10-20 04:12 UTC, kmaehashi commented
I've added an example in 8119f8f. If it's ok for you, please proceed to merge!

2021-10-20 04:12 UTC, kmaehashi approved these changes

2021-10-20 05:26 UTC, merged