Add mypy check for examplex
pfnet/pytorch-pfn-extras pull request #351
Opened 2021-09-22 09:18 UTC by asi1024

Depends on https://github.com/pfnet/pytorch-pfn-extras/pull/348.

2021-09-27 05:41 UTC, kmaehashi requested changes

2021-09-27 05:41 UTC, kmaehashi commented on example/mnist_custom_logic.py
> +class CustomLogic(ppe.handler.Logic):  # type: ignore[misc]
Can we avoid this?

2021-09-27 05:41 UTC, kmaehashi commented on example/mnist_ddp.py
> +    train_sampler = torch.utils.data.DistributedSampler(  # type: ignore[var-annotated]
Can we avoid this?

2021-09-27 05:41 UTC, kmaehashi commented on example/mnist_ddp.py
> +    test_loss = 0.
```suggestion
    test_loss = 0.0
```

2021-09-27 09:47 UTC, asi1024 commented
/test

2021-09-27 10:36 UTC, kmaehashi commented
Could you fix flake8 errors?

2021-09-27 11:27 UTC, asi1024 commented
/test

2021-09-27 12:57 UTC, asi1024 commented
PTAL!

2021-09-30 04:27 UTC, kmaehashi commented on pytorch_pfn_extras/training/manager.py
> +            self._models = dict(models)
Can this be avoided?

2021-09-30 04:27 UTC, kmaehashi commented on pytorch_pfn_extras/training/manager.py
> +            self._optimizers = dict(optimizers)
ditto

2021-09-30 06:16 UTC, kmaehashi commented
/test

2021-09-30 06:16 UTC, kmaehashi approved these changes

2021-09-30 08:28 UTC, asi1024 commented
/test

2021-09-30 08:48 UTC, merged