New comparer interface
pfnet/pytorch-pfn-extras pull request #400
Opened 2021-10-20 14:20 UTC by asi1024

2021-11-02 06:00 UTC, kmaehashi requested changes
Thanks~! :+1:

2021-11-02 06:00 UTC, kmaehashi commented on pytorch_pfn_extras/utils/comparer.py
> +        with concurrent.futures.ThreadPoolExecutor(max_workers=n_workers) as executor:
Could you add a path to run without ThreadPoolExecutror when `self._concurrency == None`?

2021-11-02 08:09 UTC, asi1024 commented on pytorch_pfn_extras/utils/comparer.py
> +        get_dict: Callable[[], Dict[str, Any]],
Because I don't want to call `model.state_dict()` when model parameters are not compared.

2021-11-02 09:32 UTC, asi1024 commented
PTAL.
/test

2021-11-04 06:23 UTC, kmaehashi approved these changes

2021-11-04 06:23 UTC, merged