Add JITRuntime test
pfnet/pytorch-pfn-extras pull request #406
Opened 2021-10-22 14:47 UTC by asi1024

~Depends on #400 and #405~

TODO: need to be fixed after supporting intermediate variable comparison in Comparer. (added by @kmaehashi)

2021-11-08 13:31 UTC, asi1024 commented
Rebased. PTAL.
/test

2021-11-10 09:50 UTC, asi1024 commented
/test

2021-11-12 09:36 UTC, kmaehashi requested changes
LGTM except nits!

2021-11-12 18:44 UTC, asi1024 commented on tests/pytorch_pfn_extras_tests/runtime_tests/test_jit_runtime.py
> +                self._traced_mod = torch.jit.trace_module(new_module, {"forward": args})
Fixes https://github.com/pfnet/pytorch-pfn-extras/pull/406#discussion_r748066213.
```suggestion
                warnings.simplefilter('ignore')
                self._traced_mod = torch.jit.trace_module(new_module, {"forward": args})
                warnings.simplefilter('error')
```

2021-11-12 18:45 UTC, asi1024 commented
/test

2021-11-15 07:56 UTC, asi1024 commented
/test

2021-11-15 09:40 UTC, kmaehashi commented
/test

2021-11-15 09:40 UTC, kmaehashi submitted a review, later dismissed

2021-11-15 10:25 UTC, asi1024 commented
/test

2021-11-15 13:22 UTC, asi1024 commented
/test

2021-11-16 08:43 UTC, asi1024 commented
/test

2021-11-16 08:48 UTC, kmaehashi commented on tests/pytorch_pfn_extras_tests/runtime_tests/test_jit_runtime.py
> +                    self._traced_mod = torch.jit.trace_module(
For record:
* Due to PyTorch bug, this raises `SystemError` when `filterwarnings = error` is set in `pytest.ini`.
* Tried to add `ignore::torch.jit.TracerWarning:torch.(?!jit)` to the filter to emulate https://github.com/pytorch/pytorch/blob/v1.10.0/torch/jit/_trace.py#L531-L540, however this broke EnsureShape JIT test for some reason. (#430)
* `catch_warnings` is thread-unsafe but we accept it for now as we don't have a plan to use pytest-xdist.

2021-11-16 08:58 UTC, kmaehashi approved these changes

2021-11-16 09:38 UTC, merged